### ISSUE TITLE
Fix memory error on STM32

### ISSUE THREAD

**Issue by soulsyrup** [Unlimited-Research-Cooperative/Bio-Silicon-Synergetic-Intelligence-System#30]
![Image](https://github.com/Unlimited-Research-Cooperative/Bio-Silicon-Synergetic-Intelligence-System/assets/121889618/7e3d55dc-77c5-4063-97da-523e04d898f4)

File used in the above screenshot - [CMSIS-DAP-V1-F103.hex](https://github.com/x893/CMSIS-DAP/blob/master/Firmware/STM32/hex/CMSIS-DAP-V1-F103.hex)

**Comment by Raghav67816** [comment]
Firstly, make sure that you have a FlashLoader folder in your STM32CubeProgrammer Installation directory

**Comment by MarkVeerasingam** [comment]
hi - i'll follow up with you on dc @soulsyrup 
- is this with the freeeg board(STM32H743)?, - if so could it be that you have an external memory configured in ST-Link Utility/External Loader menu that do not mach with your hardware on your custom board?

**Comment by Raghav67816** [comment]
Maybe you can try loading the firmware using terminal that might help in debugging. You can also check logs of this application.

**Comment by soulsyrup** [comment]
fixed it. added STM32CubeProgrammer to systems path

heres the steps ( change export path to your actual STM32CubeProgrammer/bin location )


nano ~/.bashrc
export PATH="$PATH:/home/vincent/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin"
source ~/.bashrc
echo $PATH
STM32_Programmer_CLI -l stlink
STM32_Programmer_CLI -c port=SWD apIndex=0 -w /home/vincent/Downloads/CMSIS-DAP-V1-F103.hex 0x08000000

**Comment by Raghav67816** [comment]
The task is completed and already marked as done closing this issue.
